### ISSUE TITLE
Display some metadata for hierarchical dendrogram in the dot plot?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [Simon-Leonard/FlexDotPlot_paper#1]
Hi, @Simon-Leonard -- Thank you so much for the upgraded dot plot visualisation. 

I was wondering if there is a way to show additional metadata variables in the dot plot on which the hierarchical dendrogram can be performed instead of being performed on the clusters, like in a heatmap? 

For example, in our data, we have data belonging to stimulated vs non-stimulated groups and disease vs no-disease groups, most clusters belong to all groups. It would be great to show whether the hierarchical clustering would put certain groups closer to each other than to other groups?

Thank you for your help.

**Comment by Simon-Leonard** [comment]
Hi @denvercal1234GitHub , 

Hierarchical dendrogram can be performed on additional metadata but these variables cannot be displayed on the side off the dotplot. That would be a very interesting feature to add, like the annotation_row and annotation_col parameters in the pheatmap package/function.

Maybe you can try to use vertical_coloring/horizontal_coloring parameters but it will be limited on 1 variable only.

Best,
Simon
